version: '3.7'
services:
  api:
    build:
      context: ./backend
    command: yarn run dev
    volumes:
      - ./backend/src:/usr/app/src
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_PORT=27017
      - MONGO_URL=api_mongo
    depends_on: 
     - api_mongo
  
  api_mongo:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodb_api: 